### ISSUE TITLE
Doesnt display anything

### ISSUE THREAD

**Issue by businessclimber** [mykle1/MMM-Earthquake#3]
Hi

Thank you for sharing this feature. I have cloned the git url. However it just shows as  "EARTHQUAKE!..." with no further data as displayed in the screenshot. 

Please help!

**Comment by GoodWillGustin** [comment]
Just installed and I am having the same issue. I even defaulted the config back to New York, NY from my town and still not loading in MM. Just says "EARTHQUAKE!..."

**Comment by mykle1** [comment]
Wow, sorry about the huge delay in responding. It seems the api has changed things. I'll see what I can do to get this back up and running, or something to replace it.

**Comment by raphatapi** [comment]
Same issue here. Any news? Just had an Earthquake here in Utah. Thank you!

**Comment by mykle1** [comment]
"This API is currently disabled due to heavy user demand."

Sorry but there is nothing I can do about that

**Comment by raphatapi** [comment]
Thanks for your reply

**Comment by ArnoStrasbourg** [comment]
Hi, perhaps can you delete the module from github or put a remarque somewhere to advertise about the issue....

**Comment by mykle1** [comment]
My apologies. I've marked the readme of the repo
